language: node_js
node_js:
- '10'
sudo: false
branches:
  only:
  - master
install:
- sudo apt install xvfb
- npm install -g @angular/cli
before_script:
- npm install
cache:
  directories:
  - node_modules
script:
- npm run lint
- npm run build
- ng build --prod
#- sonar-scanner
notifications:
  slack:
    secure: JhojPd0PPmxBUSgkgbdSKWCGwAPr8NjqmE3bu4T7eucvFmb2NiO4Rrn+dxIX4Twy18GDpBKC/QldSHgWGAvNrWRP0fYjQCoBVdKMezKfazl8ASMFHgHoPUEUws66+HF8474guH6l5IPUfIsgqK2USv+oXyUrQhYjeyB/kL/nwLq1bYpVO7RpLJv2YqymnTxelqibANVLxw+S1bxXAYxmFDMbLsurcY5X+iaawCVB5AugAFdEUihSoDwXTezA59ntntmRmbKZk7mirIIXoHwvZPTBlD5gAZcofcAiuANnH7DQfkpKp9ZhTMO8yU4Zd+UGYXhKSWe9OPUM63jgnDW5ETZ0VUQLvSx3s4E1mpBv+dZ/GqaJr8CCnHlJEdfalKAa8glctWPWDQQZ3viV597oEMbhwYjMdpl16n8oxVaHj9RZ2n5XSc2hna9AnvHOxs069xhxj+a8mQjtPxZiC56LtMOWR8ReRywR1bI5nPl//8AtoKOhooF/elVL8gIqIwmR6OayRBHGyIGgO2Nkas+LhHE1/p21lsMsOoj5wYk8ckAt8KL6OJLI/1CYKnYqioCDGAPAMt+a/+QwYp2Tpn9bkk1TUzUJK9MjB1lZsShicb2UWucXJitlE5Iem8xR45xyIooUI5xEtG9qTfSkUva+Xt1QcZ4vMZJSI//+hxZ1BVI=
#addons:
#  sonarcloud:
#    organization: sytw12018
#    token:
#      secure: g14dQCLXceVQmEV3fe/0dnZ6BUczWtIf3ABDBPOA6f2DDKgmdFBb99/3u8EwQ87g7PdpgTFNmxyG6TkAVGrNR+It0w3JW8rtXitMpiVz1Z8kCAS9JVHdjg7cIVoCirQmcH20RQRFt5BRFoGAIH1CHt/8d6KQpxJnQ39K5ofo2WD02N3G/R6zb+5bQm9knrAsqde38ADmLW+qO1WpMJoipRicR+XHkZvVrLMpgsphUyfllBwLqgWnJeBb98ry8qzVLyD8CumuEpq8C3Cu3Gfy5CJ3VjnXNw/tdvZ+gB8gVz5VjXIHCm3Z9C+C0uclJmTLHPYidyQv+DNUQ7u2SP4RCPkHF8rSOhGAYi/hReOD3zl6z2XhnM3J+IwVkvFBTr7yWvK3cLKdWVFMVeg+BlXGIAKSJDukT73Zv9vB57Eq20orJR4dUcKyVT7jD2h1SJ5FRvrQtSRTuUteGTLeuiaHHsq8o+0chl1uc3DS3WOnIz98LwpyU8HP3+5PnMx+HBuIosIIltNdwkOT1dPz/npp4T9kwQnmmRmadw7JEFMTpEjE5nm8pCCyvlypnmRv4+alGD6jA467jSQRkBYmsvu0217fR04MBNcDRAWkTGobh6iG0I9anc+VIZ+IvNzBriEv5/bDZqYYr89Xr2HzNlEMy2oHG5cQOooqVYoIVDC75xA=
before_install:
- openssl aes-256-cbc -K $encrypted_aabe89096d3d_key -iv $encrypted_aabe89096d3d_iv
  -in ULL.conf.enc -out ULL.conf -d

